apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: httpbin
  name: httpbin
  namespace: production
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: httpbin
status:
  loadBalancer: {}
