apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: petstore
  name: petstore
  namespace: production
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: petstore
status:
  loadBalancer: {}
