apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpbin
  name: httpbin
  namespace: staging
spec:
  containers:
  - image: kennethreitz/httpbin:latest
    name: httpbin
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
