name: Lint Tyk APIs

on:
   pull_request:
     paths:
       - 'infrastructure/staging/tyk/**'
   workflow_dispatch:
   workflow_call:

jobs:
   tyk-lint:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        actions: read
        checks: write
      steps:
        - 
            name: Checkout
            uses: actions/checkout@v4
        -
            name: Install Spectral
            run: npm install -g @stoplight/spectral-cli
        -
            name: Lint api definitions
            uses: stoplightio/spectral-action@latest
            with:
                file_glob: infrastructure/staging/tyk/apis/api-*.json
                spectral_ruleset: infrastructure/staging/tyk/tykapi-ruleset.yaml
            continue-on-error: true
        -
            name: Lint oas api definitions
            uses: stoplightio/spectral-action@latest
            with:
                file_glob: infrastructure/staging/tyk/apis/oas-*.json
                spectral_ruleset: infrastructure/staging/tyk/tykoas-ruleset.yaml
            continue-on-error: true