name: Tyk Sync (Staging)

on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/staging/tyk/**'
    branches: 
      - main

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  tyk-lint:
    uses: ./.github/workflows/tyk-lint.yml
    with:
      environment: staging

  tyk-sync-staging:
    needs: tyk-lint
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create .tyk.json
      run: |
        echo '{' > .tyk.json
        echo '  "type": "apidef",' >> .tyk.json
        echo '  "files": [' >> .tyk.json
        find . -type f -name '*.json' -path './infrastructure/staging/tyk/apis/*' -exec echo '    {"file": "{}"},' \; | sed '$ s/,$//' >> .tyk.json
        echo '  ],' >> .tyk.json
        echo '  "policies": [' >> .tyk.json
        find . -type f -name '*.json' -path './infrastructure/staging/tyk/policies/*' -exec echo '    {"file": "{}"},' \; | sed '$ s/,$//' >> .tyk.json
        echo '  ],' >> .tyk.json
        echo '  "assets": [' >> .tyk.json
        find . -type f -name '*.json' -path './infrastructure/staging/tyk/assets/*' -exec echo '    {"file": "{}"},' \; | sed '$ s/,$//' >> .tyk.json
        echo '  ]' >> .tyk.json
        echo '}' >> .tyk.json
        cat .tyk.json

    - name: Replace Target Url hostname
      env: 
        TARGET_HOST: ${{ vars.API_TARGET_HOST }}
        DIRECTORY: "./infrastructure/staging/tyk/apis/"
      run: |
        chmod +x ./.github/scripts/replace_target_host.sh
        ./.github/scripts/replace_target_host.sh

    - name: Sync with Tyk
      run: |
        echo 'Sync config to ${TYK_DASHBOARD_URL}'
        docker run -v ${{ github.workspace }}:/app/data ${TYK_SYNC_REPO}:${TYK_SYNC_VERSION} sync --path /app/data --dashboard ${TYK_DASHBOARD_URL} --secret ${TYK_DASHBOARD_SECRET}
      env:
        TYK_SYNC_REPO: ${{ vars.TYK_SYNC_REPO }}
        TYK_SYNC_VERSION: ${{ vars.TYK_SYNC_VERSION }}
        TYK_DASHBOARD_URL: ${{ vars.TYK_DASHBOARD_URL }}
        TYK_DASHBOARD_SECRET: ${{ secrets.TYK_DASHBOARD_SECRET }}
