name: Lint Tyk APIs

on:
   pull_request:
    paths:
      - 'infrastructure/staging/tyk/**'
   workflow_dispatch:
   workflow_call:

jobs:
   tyk-lint:
      runs-on: ubuntu-latest
      steps:
        - 
            name: Checkout
            uses: actions/checkout@v4
        - 
            name: Setup node
            uses: actions/setup-node@v3
            with:
                node-version: 20.10.0
                cache: 'npm'
        -
            name: Install Spectral
            run: npm install -g @stoplight/spectral-cli
        -
            name: Lint api definitions
            run: spectral lint --ruleset infrastructure/staging/tyk/tykapi-ruleset.yaml infrastructure/staging/tyk/apis/api-*.json 
            continue-on-error: true
        -
            name: Lint oas api definitions
            run: spectral lint --ruleset oas3 infrastructure/staging/tyk/apis/oas-*.json
            continue-on-error: true